export {
  createSpecReadService,
  SPEC_ENTITY_KINDS,
  SPEC_HIERARCHY_RELATION_TYPES,
  SPEC_READ_LIMITS,
  type SpecDetailProjection,
  type SpecEntityKind,
  type SpecHierarchyProjection,
  type SpecHierarchyRelationProjection,
  type SpecHierarchyRelationType,
  type SpecIndexProjection,
  type SpecListPageProjection,
  type SpecListRequest,
  type SpecListResult,
  type SpecReadAvailability,
  type SpecReadService,
  type SpecShowResult,
  type SpecSummaryProjection,
  type SpecWikiReadPort,
} from "./service.js";
