import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import {
  KNOWN_LEGACY_INSTRUCTION_SHA256,
  MAX_MANAGED_INSTRUCTION_PREVIEW_BYTES,
  MEX_INSTRUCTIONS_END,
  MEX_INSTRUCTIONS_START,
  planManagedInstructionEdit,
  renderManagedInstructionBlock,
} from "../instructions.js";

describe("managed MEX instruction blocks", () => {
  it("renders every required policy with client-specific invocation syntax", () => {
    const claude = renderManagedInstructionBlock("claude");
    const codex = renderManagedInstructionBlock("codex");

    for (const block of [claude, codex]) {
      expect(block).toContain(
        "At the start of every session, read `.mex/AGENTS.md` and `.mex/ROUTER.md`",
      );
      expect(block).toContain("explicit contributions to project knowledge");
      expect(block).toContain("durable team handoffs");
      expect(block).toContain("Invoke them automatically when intent clearly matches");
      expect(block).toContain("ordinary GROW upkeep remains available without Inbox");
      expect(block).toContain("mex logging --json");
      expect(block).toContain("`significant`");
      expect(block).toContain("`checkpoints`");
      expect(block).toContain("`manual`");
      expect(block).toContain("Honor explicit user log requests in every mode");
      expect(block).toContain("never suppress mandatory workflow Activity or recovery audit records");
      expect(block).toContain('mex timeline --query "subject phrase" --file src/example.ts --limit 10 --json');
      expect(block).toContain("historical evidence, not accepted current knowledge");
      expect(block).toContain(
        "mention MEX and the relevant finding naturally in your explanation",
      );
      expect(block).toContain("unless the retrieved data actually provides it");
      expect(block).toContain("local draft is checkout-only and nothing is shared");
      expect(block).toContain("canonical artifact is written to the working tree");
      expect(block).toContain("requires commit/push to share");
      expect(block).toContain("Skill activation is not approval for canonical actions");
    }
    expect(claude).toContain("`/mex-inbox`");
    expect(claude).toContain("`/mex-relay`");
    expect(claude).not.toContain("$mex-");
    expect(codex).toContain("`$mex-inbox`");
    expect(codex).toContain("`$mex-relay`");
    expect(codex).not.toContain("/mex-");
  });

  it("creates an absent file and is an exact no-op on the generated bytes", () => {
    const created = planManagedInstructionEdit("claude", null);
    expect(created).toMatchObject({ action: "create", reason: "absent" });
    expect(created.instructionChange).toEqual({
      scope: "create",
      before: null,
      after: renderManagedInstructionBlock("claude"),
    });
    expect(asText(created.desiredBytes)).toBe(`${renderManagedInstructionBlock("claude")}\n`);

    expect(planManagedInstructionEdit("claude", created.desiredBytes!)).toEqual({
      action: "noop",
      reason: "exact",
    });
  });

  it("preserves a handwritten UTF-8 BOM and all original bytes when appending", () => {
    const original = Buffer.from("\ufeff# Hand written\r\nKeep this exactly.\r\n", "utf8");
    const edit = planManagedInstructionEdit("codex", original);

    expect(edit).toMatchObject({ action: "update", reason: "append" });
    expect(edit.instructionChange).toEqual({
      scope: "append",
      before: null,
      after: renderManagedInstructionBlock("codex", "\r\n"),
    });
    const desired = Buffer.from(edit.desiredBytes!);
    expect(desired.subarray(0, original.length)).toEqual(original);
    expect(asText(desired)).toContain("\r\n<!-- mex-agent:skills:start -->\r\n");
    expect(asText(desired)).toContain("`$mex-inbox`");
  });

  it("replaces only a valid managed block and preserves BOM/CRLF bytes around it", () => {
    const oldBlock = [
      MEX_INSTRUCTIONS_START,
      "old managed content",
      MEX_INSTRUCTIONS_END,
    ].join("\r\n");
    const prefix = Buffer.from("\ufeff# User heading\r\n\r\n", "utf8");
    const suffix = Buffer.from("\r\n\r\nUser footer\r\n", "utf8");
    const current = Buffer.concat([prefix, Buffer.from(oldBlock), suffix]);

    const edit = planManagedInstructionEdit("claude", current);
    expect(edit).toMatchObject({ action: "update", reason: "replace" });
    expect(edit.instructionChange).toEqual({
      scope: "replace",
      before: oldBlock,
      after: renderManagedInstructionBlock("claude", "\r\n"),
    });
    const desired = Buffer.from(edit.desiredBytes!);
    expect(desired.subarray(0, prefix.length)).toEqual(prefix);
    expect(desired.subarray(desired.length - suffix.length)).toEqual(suffix);
    expect(asText(desired)).toContain("`/mex-relay`");
    expect(asText(desired)).not.toContain("old managed content");
  });

  it("migrates only an exact known legacy hash and keeps CRLF output consistent", () => {
    const legacy = Buffer.from("MEX generated legacy\r\nsecond line\r\n", "utf8");
    const hash = createHash("sha256").update(legacy).digest("hex");
    const migrated = planManagedInstructionEdit("codex", legacy, [hash]);

    expect(migrated).toMatchObject({ action: "migrate", reason: "legacy" });
    expect(migrated.instructionChange).toEqual({
      scope: "known-legacy-migration",
      before: null,
      after: renderManagedInstructionBlock("codex", "\r\n"),
    });
    expect(asText(migrated.desiredBytes)).toBe(
      `${renderManagedInstructionBlock("codex", "\r\n")}\r\n`,
    );

    const modified = Buffer.concat([legacy, Buffer.from("user edit\r\n")]);
    expect(planManagedInstructionEdit("codex", modified, [hash])).toMatchObject({
      action: "update",
      reason: "append",
    });
    expect(KNOWN_LEGACY_INSTRUCTION_SHA256.claude).toContain(
      "2ba41ed19c039420d60e2f6da930b9c7de999ecfd5f96fd236fd39df8c952eec",
    );
    expect(KNOWN_LEGACY_INSTRUCTION_SHA256.claude).toContain(
      "ee60a376430adccfcc24b5c880f6b5a449c1c959a039dc047f057bd80907ee91",
    );
    expect(KNOWN_LEGACY_INSTRUCTION_SHA256.codex).toContain(
      "ee60a376430adccfcc24b5c880f6b5a449c1c959a039dc047f057bd80907ee91",
    );
  });

  it.each([
    ["start only", `${MEX_INSTRUCTIONS_START}\nbody\n`],
    ["end only", `body\n${MEX_INSTRUCTIONS_END}\n`],
    ["duplicate", `${MEX_INSTRUCTIONS_START}\na\n${MEX_INSTRUCTIONS_END}\n${MEX_INSTRUCTIONS_START}\nb\n${MEX_INSTRUCTIONS_END}\n`],
    ["nested", `${MEX_INSTRUCTIONS_START}\n${MEX_INSTRUCTIONS_START}\na\n${MEX_INSTRUCTIONS_END}\n${MEX_INSTRUCTIONS_END}\n`],
    ["reversed", `${MEX_INSTRUCTIONS_END}\nbody\n${MEX_INSTRUCTIONS_START}\n`],
    ["non-standalone", `prose ${MEX_INSTRUCTIONS_START}\nbody\n${MEX_INSTRUCTIONS_END}\n`],
  ])("fails closed for %s markers", (_name, content) => {
    expect(planManagedInstructionEdit("claude", Buffer.from(content))).toEqual({
      action: "conflict",
      reason: "malformed-markers",
    });
  });

  it("fails closed on non-UTF-8 bytes", () => {
    expect(planManagedInstructionEdit("claude", Uint8Array.from([0xc3, 0x28]))).toEqual({
      action: "conflict",
      reason: "invalid-encoding",
    });
  });

  it("fails closed rather than exposing an oversized previous managed block", () => {
    const content = [
      MEX_INSTRUCTIONS_START,
      "x".repeat(MAX_MANAGED_INSTRUCTION_PREVIEW_BYTES),
      MEX_INSTRUCTIONS_END,
    ].join("\n");

    expect(planManagedInstructionEdit("claude", Buffer.from(content))).toEqual({
      action: "conflict",
      reason: "managed-block-too-large",
    });
  });
});

function asText(bytes: Uint8Array | undefined): string {
  expect(bytes).toBeDefined();
  return Buffer.from(bytes!).toString("utf8");
}
